[package]
name = "bevy_aseprite_ultra"
version = "0.1.0"
edition = "2021"
authors = ["Lorenz Mielke"]
description = "A Bevy plugin for directly loading spritesheets and animations from aseprite binary files with hot reloading support."
keywords = ["bevy", "aseprite", "atlas", "loader", "animation"]
repository = "https://github.com/Lommix/bevy_aseprite_ultra.git"
license = "MIT"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
  "bevy_sprite",
  "bevy_asset",
  "bevy_ui",
] }
anyhow = "1.0.75"
aseprite-loader = "0.2.0"

[features]
dev = ["bevy/multi-threaded", "bevy/wayland", "bevy/file_watcher"]
